name: build
on:
  push: ~
  pull_request: ~
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]

    steps:
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Git User config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: Install Dependencies
        run: |
          pip freeze
          pip install -r requirements-dev.txt
          pip install coveralls
          pip freeze

      - run: pylint organizer
        if: matrix.python-version != '3.9'

      - run: coverage run --source=organizer -m pytest

      - run: python setup.py build

      - name: Coveralls
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
